In [2]:
import cv2
print(cv2.__version__)

4.12.0


In [3]:
import numpy as np
import matplotlib.pyplot as plt
image = np.full((16,16,3),100, dtype='uint8')
image[4:10,4:5] = [255,103,31]
image[4:10,5:6] = [255,255,255]
image[4:10,6:7] = [0,255,0]
cv2.imshow('image',image)
cv2.imwrite('image.jpg',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [4]:
image= cv2.imread('me.jpeg')
image= cv2.GaussianBlur(image,(5,5),0)
print(type(image))
cv2.imshow('image',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>


In [5]:
import cv2
print(cv2.__version__)
print(cv2.__file__)

4.12.0
c:\Users\aditi\Downloads\INTERN AI\srm\lib\site-packages\cv2\__init__.py


In [6]:
import cv2

print(hasattr(cv2, "data"))
print(cv2.data.haarcascades)


True
c:\Users\aditi\Downloads\INTERN AI\srm\lib\site-packages\cv2\data\


In [7]:
import cv2

model = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

print(model.empty())

False


In [8]:
import cv2

print(dir(cv2)[:30])

['ACCESS_FAST', 'ACCESS_MASK', 'ACCESS_READ', 'ACCESS_RW', 'ACCESS_WRITE', 'ADAPTIVE_THRESH_GAUSSIAN_C', 'ADAPTIVE_THRESH_MEAN_C', 'AGAST_FEATURE_DETECTOR_AGAST_5_8', 'AGAST_FEATURE_DETECTOR_AGAST_7_12D', 'AGAST_FEATURE_DETECTOR_AGAST_7_12S', 'AGAST_FEATURE_DETECTOR_NONMAX_SUPPRESSION', 'AGAST_FEATURE_DETECTOR_OAST_9_16', 'AGAST_FEATURE_DETECTOR_THRESHOLD', 'AKAZE', 'AKAZE_DESCRIPTOR_KAZE', 'AKAZE_DESCRIPTOR_KAZE_UPRIGHT', 'AKAZE_DESCRIPTOR_MLDB', 'AKAZE_DESCRIPTOR_MLDB_UPRIGHT', 'AKAZE_create', 'ALGO_HINT_ACCURATE', 'ALGO_HINT_APPROX', 'ALGO_HINT_DEFAULT', 'AffineFeature', 'AffineFeature_create', 'AgastFeatureDetector', 'AgastFeatureDetector_AGAST_5_8', 'AgastFeatureDetector_AGAST_7_12d', 'AgastFeatureDetector_AGAST_7_12s', 'AgastFeatureDetector_NONMAX_SUPPRESSION', 'AgastFeatureDetector_OAST_9_16']


In [9]:
import os
import cv2

print(cv2.data.haarcascades)
print(os.path.exists(cv2.data.haarcascades + "haarcascade_frontalface_default.xml"))

c:\Users\aditi\Downloads\INTERN AI\srm\lib\site-packages\cv2\data\
True


In [10]:
import cv2
import numpy as np
image = cv2.imread('me.jpeg')

model = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
faces = model.detectMultiScale(image)
print(faces)




[[ 536  641  136  136]
 [ 831 1237   82   82]
 [ 781  688   85   85]
 [ 470 1130   85   85]]


In [11]:
import cv2
import numpy as np
image = cv2.imread('me.jpeg')

model = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
faces = model.detectMultiScale(image)
print(faces)




[[ 536  641  136  136]
 [ 831 1237   82   82]
 [ 470 1130   85   85]
 [ 781  688   85   85]]


In [12]:
import cv2
import numpy as np
image = cv2.imread('me.jpeg')

model = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
faces = model.detectMultiScale(image)
print(faces)





[[ 536  641  136  136]
 [ 831 1237   82   82]
 [ 470 1130   85   85]
 [ 781  688   85   85]]


In [13]:
for face in faces:
    x, y, w, h = face
    cv2.rectangle(image, (x,y), (x+w, y+h),(255,0,0), 3)
cv2.imwrite('me1ans.jpg', image)

True

In [14]:
import cv2
import numpy as np
img = cv2.imread('me.jpeg')

face_detector1 = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_detector1 = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_eye.xml")

faces = face_detector1.detectMultiScale(img)
eyes = eye_detector1.detectMultiScale(img)

for x, y, w,h in faces:
    cv2.rectangle(img, (x,y), (x+w, y+h), (255,0,0),3)
    face = img[y:y+h, x:x+w]

for x, y, w,h in eyes:
    cv2.rectangle(img, (x,y), (x+w, y+h), (255,0,0),3)
    eye = img[y:y+h, x:x+w]

cv2.imshow('me',img)
cv2.waitKey(5000)
faces = model.detectMultiScale(image)
print(faces)
eyes = model.detectMultiScale(image)
print(eyes)

[[ 832 1238   79   79]
 [ 538  641  135  135]
 [ 778  689   82   82]]
[[ 832 1238   79   79]
 [ 538  641  135  135]
 [ 778  689   82   82]]


In [15]:
print (x_train.shape)


(60000, 28, 28, 1)


In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

model = Sequential()

model.add(
    Conv2D(
        32,
        (3,3),
        strides=(1,1),
        padding="same",
        activation="relu",
        input_shape=(32,32,3)
    )
)

c:\Users\aditi\Downloads\INTERN AI\srm\lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [21]:
# ==========================
# CNN on MNIST Dataset
# ==========================

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense

# Set random seed for reproducibility
tf.random.set_seed(42)

# --------------------------
# Load the MNIST dataset
# --------------------------
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Display dataset information
print("Training Images :", x_train.shape)
print("Training Labels :", y_train.shape)
print("Testing Images  :", x_test.shape)
print("Testing Labels  :", y_test.shape)

# --------------------------
# Data Preprocessing
# --------------------------

# Convert to float32 and normalize pixel values
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# Add channel dimension
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

# --------------------------
# Build CNN Model
# --------------------------

model = Sequential([
    Input(shape=(28, 28, 1)),

    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),

    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),

    Flatten(),

    Dense(128, activation='relu'),

    Dense(10, activation='softmax')
])

# --------------------------
# Compile Model
# --------------------------

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Display model architecture
model.summary()

# --------------------------
# Train Model
# --------------------------

history = model.fit(
    x_train,
    y_train,
    epochs=5,
    batch_size=32,
    validation_data=(x_test, y_test),
    verbose=1
)

# --------------------------
# Evaluate Model
# --------------------------

test_loss, test_accuracy = model.evaluate(x_test, y_test, verbose=0)

print("\nTest Loss     :", round(test_loss, 4))
print("Test Accuracy :", round(test_accuracy * 100, 2), "%")

Training Images : (60000, 28, 28)
Training Labels : (60000,)
Testing Images  : (10000, 28, 28)
Testing Labels  : (10000,)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_4 (Conv2D)               │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 11, 11, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 5, 5, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 1600)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │       204,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 225,034 (879.04 KB)

 Trainable params: 225,034 (879.04 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 31s 15ms/step - accuracy: 0.9603 - loss: 0.1307 - val_accuracy: 0.9877 - val_loss: 0.0448
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 30s 16ms/step - accuracy: 0.9867 - loss: 0.0426 - val_accuracy: 0.9870 - val_loss: 0.0450
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 27s 15ms/step - accuracy: 0.9915 - loss: 0.0281 - val_accuracy: 0.9866 - val_loss: 0.0468
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 26s 14ms/step - accuracy: 0.9941 - loss: 0.0198 - val_accuracy: 0.9858 - val_loss: 0.0474
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 28s 15ms/step - accuracy: 0.9957 - loss: 0.0142 - val_accuracy: 0.9897 - val_loss: 0.0378

Test Loss     : 0.0378
Test Accuracy : 98.97 %
